nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.1.cjs
#  - Yarn 配置文件，用于配置 Yarn 包管理器的行为。

# 一这个配置指定 Yarn 使用 node-modules 作为包链接.Yarn 将以传统的方式在 node_modules 目录中安装包。
# 二这个配置指定了 Yarn 的可执行文件路径。 Yarn 将使用 .yarn/releases/yarn-3.6.1.cjs 版本的 Yarn 来运行。
